let data ={
    "_id": "61f5765426952b80b9733b06",
    "username": "tylerletendre98",
    "email": "tylerletendre98@gmail.com",
    "password": "Martinbronson1029!",
    "fullname": "Tyler Letendre",
    "dexterity": "Left",
    "golfBag":[{
        "brand":"Titleist",
        "model":"TS2",
        "type":"Driver"
    }],
    "rounds": [
        {
            "holeOne": 4,
            "holeTwo": 4,
            "holeThree": 4,
            "holeFour": 4,
            "holeFive": 4,
            "holeSeven": 4,
            "holeEight": 4,
            "holeNine": 4,
            "holeTen": 4,
            "holeEleven": 4,
            "holeTwelve": 4,
            "holeThirteen": 4,
            "holeFourteen": 4,
            "holeFifteen": 4,
            "holeSixteen": 4,
            "holeSeventeen": 4,
            "holeEighteen": 4,
            "courseName": "Wannamoisett",
            "roundScore":78,
            "_id": "61f97f782633b83977a08e97"
        },
        {
            "holeOne": 4,
            "holeTwo": 4,
            "holeThree": 4,
            "holeFour": 4,
            "holeFive": 4,
            "holeSix": 4,
            "holeSeven": 4,
            "holeEight": 4,
            "holeNine": 4,
            "holeTen": 4,
            "holeEleven": 4,
            "holeTwelve": 4,
            "holeThirteen": 4,
            "holeFourteen": 4,
            "holeFifteen": 4,
            "holeSixteen": 4,
            "holeSeventeen": 4,
            "holeEighteen": 4,
            "roundScore":78,
            "courseName": "Wannamoisett",
            "underPar": true,
            "_id": "61f97fc42633b83977a08e9a"
        },
        {
            "holeOne": 4,
            "holeTwo": 4,
            "holeThree": 4,
            "holeFour": 4,
            "holeFive": 4,
            "holeSix": 4,
            "holeSeven": 4,
            "holeEight": 4,
            "holeNine": 4,
            "holeTen": 4,
            "holeEleven": 4,
            "holeTwelve": 4,
            "holeThirteen": 4,
            "holeFourteen": 4,
            "holeFifteen": 4,
            "holeSixteen": 4,
            "holeSeventeen": 4,
            "holeEighteen": 4,
            "courseName": "Wannamoisett",
            "roundScore": 72,
            "underPar": true,
            "_id": "61f9803a2633b83977a08e9d",
            "__v": 0
        }
    ]
}

module.exports = data;